# coding: utf-8

# flake8: noqa
"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from private_instagram_sdk.models.auth_body import AuthBody
from private_instagram_sdk.models.error import Error
from private_instagram_sdk.models.inline_object import InlineObject
from private_instagram_sdk.models.inline_response200 import InlineResponse200
from private_instagram_sdk.models.inline_response400 import InlineResponse400
from private_instagram_sdk.models.user import User
