# coding: utf-8

# flake8: noqa
"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from private_instagram_sdk.models.error import Error
from private_instagram_sdk.models.user import User
