# coding: utf-8

"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import private_instagram_sdk
from private_instagram_sdk.models.user import User  # noqa: E501
from private_instagram_sdk.rest import ApiException


class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser(self):
        """Test User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = private_instagram_sdk.models.user.User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
