# coding: utf-8

"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import private_instagram_sdk
from private_instagram_sdk.api.user_api import UserApi  # noqa: E501
from private_instagram_sdk.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = private_instagram_sdk.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_self_get(self):
        """Test case for users_self_get

        User Profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
