# coding: utf-8

"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import private_instagram_sdk
from private_instagram_sdk.api.auth_api import AuthApi  # noqa: E501
from private_instagram_sdk.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = private_instagram_sdk.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_login_post(self):
        """Test case for accounts_login_post

        Login user to Instagram  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
