# coding: utf-8

# flake8: noqa

"""
    Instagram API

    The Instagram Private API in OpenAPI specs.v3.0  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from private_instagram_sdk.api.auth_api import AuthApi
from private_instagram_sdk.api.user_api import UserApi

# import ApiClient
from private_instagram_sdk.api_client import ApiClient
from private_instagram_sdk.configuration import Configuration
from private_instagram_sdk.exceptions import OpenApiException
from private_instagram_sdk.exceptions import ApiTypeError
from private_instagram_sdk.exceptions import ApiValueError
from private_instagram_sdk.exceptions import ApiKeyError
from private_instagram_sdk.exceptions import ApiException
# import models into sdk package
from private_instagram_sdk.models.auth_body import AuthBody
from private_instagram_sdk.models.error import Error
from private_instagram_sdk.models.inline_object import InlineObject
from private_instagram_sdk.models.inline_response200 import InlineResponse200
from private_instagram_sdk.models.inline_response400 import InlineResponse400
from private_instagram_sdk.models.user import User

